<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>MimaEmuPrinter.Tests</AssemblyName>
		<RootNamespace>MimaEmuPrinter.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
		<PackageReference Include="PDFsharp" Version="6.2.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\MimaEmuPrinter.Core\MimaEmuPrinter.Core.csproj" />
	</ItemGroup>

</Project>